// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock" // Mocking for tests.

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// Observe provides a mock function with given fields: _a0
func (_m *Observer) Observe(_a0 float64) {
	_m.Called(_a0)
}
