GO := go
GOTEST := $(GO) test -race -timeout 5m
GOGENERATE := $(GO) generate

# Run full test suite.
test:
	$(GOTEST) ./...
	cd ./v2 && $(GOTEST) ./...

# Run tests sans Docker integration tests.
test-short:
	$(GOTEST) -short ./...
	cd ./v2 && $(GOTEST) -short ./...

generate:
	$(GOGENERATE) ./...
	cd ./v2 && $(GOGENERATE) ./...
