// Code generated by mockery v1.0.0, but then edit down to only the methods needed.

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/autoscaling"
	"github.com/aws/aws-sdk-go/service/autoscaling/autoscalingiface"

	"github.com/stretchr/testify/mock"
)

// AutoScalingAPI is an autogenerated mock type for the AutoScalingAPI type
type AutoScalingAPI struct {
	autoscalingiface.AutoScalingAPI
	mock.Mock
}

// DescribeLifecycleHooksWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *AutoScalingAPI) DescribeLifecycleHooksWithContext(_a0 context.Context, _a1 *autoscaling.DescribeLifecycleHooksInput, _a2 ...request.Option) (*autoscaling.DescribeLifecycleHooksOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *autoscaling.DescribeLifecycleHooksOutput
	if rf, ok := ret.Get(0).(func(context.Context, *autoscaling.DescribeLifecycleHooksInput, ...request.Option) *autoscaling.DescribeLifecycleHooksOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscaling.DescribeLifecycleHooksOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *autoscaling.DescribeLifecycleHooksInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecordLifecycleActionHeartbeatWithContext provides a mock function with given fields: _a0, _a1, _a2
func (_m *AutoScalingAPI) RecordLifecycleActionHeartbeatWithContext(_a0 context.Context, _a1 *autoscaling.RecordLifecycleActionHeartbeatInput, _a2 ...request.Option) (*autoscaling.RecordLifecycleActionHeartbeatOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *autoscaling.RecordLifecycleActionHeartbeatOutput
	if rf, ok := ret.Get(0).(func(context.Context, *autoscaling.RecordLifecycleActionHeartbeatInput, ...request.Option) *autoscaling.RecordLifecycleActionHeartbeatOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscaling.RecordLifecycleActionHeartbeatOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *autoscaling.RecordLifecycleActionHeartbeatInput, ...request.Option) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
